remote_theme: jackw01/jackw01.github.io
# used by SEO tag
title: Pi Pico Printer Board
author:
  name: Jack Whittaker
  url: https://jackw01.github.io
logo: https://jackw01.github.io/logo.png
defaults:
  - scope:
      path: ""
    values:
      image: images/in_printer.jpg
social:
  name: Jack Whittaker
  links:
    - https://github.com/jackw01
    - https://www.linkedin.com/in/jack-whittaker-b35961183/
# end seo
hide_first_h1: true
plugins:
  - jekyll-seo-tag
custom_buttons:
  - 1:
    url: https://github.com/jackw01/pi-pico-printer-board
    text: View on GitHub
  - 2:
    url: https://ko-fi.com/jackw01
    text: Support me on Ko-fi
